version: '3.8'
services:
  user-service:
    build: .
    image: user-service
    container_name: user_service
    ports:
      - "8080:8080"
    depends_on:
      - db1
      - db2
  db1:
    image: postgres:latest
    container_name: db1
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql

  db2:
    image: mysql:latest
    container_name: db2
    environment:
      MYSQL_DATABASE: db2
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql