app:
  data-sources:
    - name: data-base-1
      strategy: postgres
      url: jdbc:postgresql://service-db1-1:5432/db1
      table: users
      user: testuser
      password: testpass
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name
    - name: data-base-2
      strategy: mysql
      url: jdbc:mysql://service-db2-1:3306/db2?useSSL=false&allowPublicKeyRetrieval=true
      table: user_table
      user: testuser
      password: testpass
      mapping:
        id: ldap_login
        username: ldap_login
        name: name
        surname: surname